version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: iboss_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=iboss_task
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: iboss_app
    restart: always
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=1234
      - DB_NAME=iboss_task
      - ACCESS_TOKEN_SECRET=your_access_token_secret_here
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret_here
    depends_on:
      - db

volumes:
  postgres_data:
